pyside6-uic ui/dialogs/main_window.ui -o ui/dialogs/main_window.py
pyside6-uic ui/dialogs/dlg_price.ui -o ui/dialogs/dlg_price.py
pyside6-uic ui/dialogs/dlg_asph.ui -o ui/dialogs/dlg_asph.py
pyside6-uic ui/dialogs/dlg_add_asph.ui -o ui/dialogs/dlg_add_asph.py
pyside6-uic ui/dialogs/dlg_cng_asph.ui -o ui/dialogs/dlg_cng_asph.py
pyside6-uic ui/dialogs/dlg_add_clm.ui -o ui/dialogs/dlg_add_clm.py
pyside6-uic ui/dialogs/dlg_add_ctg.ui -o ui/dialogs/dlg_add_ctg.py
pyside6-uic ui/dialogs/dlg_add_factory.ui -o ui/dialogs/dlg_add_factory.py
pyside6-uic ui/dialogs/dlg_calc.ui -o ui/dialogs/dlg_calc.py
pyside6-uic ui/dialogs/dlg_vld.ui -o ui/dialogs/dlg_vld.py
pyside6-uic ui/dialogs/dlg_add_spp.ui -o ui/dialogs/dlg_add_spp.py
